revert changes

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -58,6 +58,217 @@ jobs:
         uses: styfle/cancel-workflow-action@0.9.1
         with:
           access_token: ${{ github.token }}
+
+  build-vsix:
+    name: Build VSIX
+    runs-on: ubuntu-latest
+    if: github.repository == 'microsoft/vscode-jupyter'
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Use Node ${{env.NODE_VERSION}}
+        uses: actions/setup-node@v2.4.1
+        with:
+          node-version: ${{env.NODE_VERSION}}
+
+      - name: Use Python ${{env.PYTHON_VERSION}}
+        uses: actions/setup-python@v2
+        with:
+          python-version: ${{env.PYTHON_VERSION}}
+
+      # Caching of npm packages (https://github.com/actions/cache/blob/main/examples.md#node---npm)
+      - name: Cache npm on linux/mac
+        uses: actions/cache@v3
+        with:
+          path: ~/.npm
+          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-node-
+
+      - name: Install Python libs
+        run: |
+          python -m pip --disable-pip-version-check install -t ./pythonFiles/lib/python --no-cache-dir --implementation py --no-deps --upgrade -r ./requirements.txt
+
+      - run: npm i -g vsce
+
+      - name: Build VSIX
+        uses: ./.github/actions/build-vsix
+        id: build-vsix
+
+      - uses: actions/upload-artifact@v2
+        with:
+          name: 'ms-toolsai-jupyter-insiders.vsix'
+          path: 'ms-toolsai-jupyter-insiders.vsix'
+
+  lint:
+    name: Lint
+    runs-on: ubuntu-latest
+    if: github.repository == 'microsoft/vscode-jupyter'
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Cache pip files
+        uses: actions/cache@v3
+        with:
+          path: ~/.cache/pip
+          key: ${{runner.os}}-${{env.CACHE_PIP_DEPS}}-${{env.PYTHON_VERSION}}
+
+      - name: Cache npm files
+        uses: actions/cache@v3
+        with:
+          path: ~/.npm
+          key: ${{runner.os}}-${{env.CACHE_NPM_DEPS}}-${{hashFiles('package-lock.json')}}
+
+      - name: Install dependencies (npm ci)
+        run: npm ci --prefer-offline
+
+      - name: Verify linting is turned on for changed files
+        uses: ./.github/actions/check-ignore-list
+        id: check-ignore-list
+
+      - name: Verify Translation files
+        run: npm run validateTranslationFiles
+
+      - name: Run linting on TypeScript code (eslint)
+        run: npm run lint
+
+      - name: Run prettier on TypeScript code
+        run: npx prettier 'src/**/*.ts*' --check
+
+      - name: Run prettier on JavaScript code
+        run: npx prettier 'build/**/*.js' --check
+
+      - name: Use Python ${{env.PYTHON_VERSION}}
+        uses: actions/setup-python@v2
+        with:
+          python-version: ${{env.PYTHON_VERSION}}
+
+      - name: Run Black on Python code
+        run: |
+          python -m pip install click==8.0.4
+          python -m pip install -U black
+          python -m black . --check
+        working-directory: pythonFiles
+
+      - name: Run gulp prePublishNonBundle
+        run: npm run prePublishNonBundle
+
+      - name: Cache the out/ directory
+        uses: actions/cache@v2.1.4
+        with:
+          path: ./out
+          key: ${{runner.os}}-${{env.CACHE_OUT_DIRECTORY}}-${{hashFiles('src/**')}}
+
+      - name: Check dependencies
+        run: npm run checkDependencies
+
+      - name: 'Check for telemetry edit'
+        uses: brettcannon/check-for-changed-files@v1.1.0
+        with:
+          prereq-pattern: './src/telemetry/index.ts'
+          file-pattern: 'telemetry.md'
+          skip-label: 'skip telemetry'
+          failure-message: 'TELEMETRY.md should be updated when adding or removing telemetry. Please run "npm run generateTelemetry"'
+
+    # See issue https://github.com/microsoft/vscode-jupyter/issues/10343. We need a better way to validate. Perhaps nightly.
+    # - name: Validate TELEMETRY.md file
+    #    run: npm run validateTelemetryMD
+
+    #   - name: 'Check for news entry'
+    #     uses: brettcannon/check-for-changed-files@v1.1.0
+    #     with:
+    #       file-pattern: 'news/*/*.md'
+    #       skip-label: 'skip news'
+    #       failure-message: 'News entry file missing; see news/README.md for instructions (the ${skip-label} label can be used to pass this check)'
+
+  ts_tests:
+    name: Type Script Tests
+    runs-on: ${{ matrix.os }}
+    if: github.repository == 'microsoft/vscode-jupyter'
+    strategy:
+      fail-fast: false
+      matrix:
+        os: ["ubuntu-latest", "windows-latest"]
+        test-suite: [ts-unit]
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Use Node ${{env.NODE_VERSION}}
+        uses: actions/setup-node@v2.4.1
+        with:
+          node-version: ${{env.NODE_VERSION}}
+
+      # Caching of npm packages (https://github.com/actions/cache/blob/main/examples.md#node---npm)
+      - name: Cache npm on linux/mac
+        uses: actions/cache@v3
+        if: matrix.os != 'windows-latest'
+        with:
+          path: ~/.npm
+          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-node-
+
+      - name: Get npm cache directory
+        if: matrix.os == 'windows-latest'
+        id: npm-cache
+        run: |
+          echo "::set-output name=dir::$(npm config get cache)"
+      - name: Cache npm on windows
+        uses: actions/cache@v3
+        if: matrix.os == 'windows-latest'
+        with:
+          path: ${{ steps.npm-cache.outputs.dir }}
+          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-node-
+
+      - name: Cache compiled TS files
+        # Use an id for this step so that its cache-hit output can be accessed and checked in the next step.
+        id: out-cache
+        uses: actions/cache@v3
+        with:
+          path: ./out
+          key: ${{runner.os}}-${{env.CACHE_OUT_DIRECTORY}}-${{hashFiles('src/**')}}
+
+      - name: Install dependencies (npm ci)
+        run: npm ci --prefer-offline
+
+      - name: Compile if not cached
+        run: npm run prePublishNonBundle
+        if: steps.out-cache.outputs.cache-hit != 'true'
+        env:
+          CI_JUPYTER_FAST_COMPILATION: 'true'
+
+      - name: Run TypeScript unit tests
+        id: test_unittests
+        run: npm run test:unittests
+
+      - name: Verify there are no unhandled errors
+        run: npm run verifyUnhandledErrors
+
+      - name: Publish Test Report
+        uses: scacap/action-surefire-report@v1
+        if: steps.test_unittests.outcome == 'failure' && failure()
+        with:
+          github_token: ${{ secrets.TOKEN_TO_CREATE_RELEASE }}
+          report_paths: ${{ env.TEST_RESULTS_GLOB }}
+          check_name: Ts-Unit Test Report
+
+      - name: Create coverage folder (if not created)
+        run: npm run createNycFolder
+
+      # Upload unit test coverage reports for later use in the "reports" job.
+      - name: Upload unit test coverage reports
+        uses: actions/upload-artifact@v2
+        if: "(success() || failure()) && !contains(github.ref, 'refs/heads/release')"
+        with:
+          name: ${{runner.os}}-${{env.COVERAGE_REPORTS}}
+          path: .nyc_output
+          retention-days: 1
+
   vscodeTests:
     name: Tests # These tests run with Python extension & real Jupyter
     runs-on: ${{ matrix.os }}
@@ -68,9 +279,9 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        jupyter: [raw]
-        python: [nonConda]
-        pythonVersion: ['3.9']
+        jupyter: [raw, local]
+        python: [nonConda, conda]
+        pythonVersion: ['3.9', '3.10']
         webOrDesktop: ['']
         # Whether we're using stable (<empty>) or pre-release versions of Python packages.
         # When installing pre-release versions, we're only focused on jupyter & related packages.
@@ -79,44 +290,44 @@ jobs:
         # We're not running CI on macOS for now because it's one less matrix entry to lower the number of runners used,
         # macOS runners are expensive, and we assume that Ubuntu is enough to cover the UNIX case.
         os: [ubuntu-latest]
-        # # More details on includes/excludes can be found here https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-including-additional-values-into-combinations
-        # # Basically with exclude, you can exclude any of the combinations from the result matrix.
-        # # & with include, you can include additional items to the result matrix.
-        # include:
-        #   - jupyter: remote # We don't care how remote is started (we only want to test connecting to it)
+        # More details on includes/excludes can be found here https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-including-additional-values-into-combinations
+        # Basically with exclude, you can exclude any of the combinations from the result matrix.
+        # & with include, you can include additional items to the result matrix.
+        include:
+          - jupyter: remote # We don't care how remote is started (we only want to test connecting to it)
+            python: nonConda
+            pythonVersion: '3.9'
+            webOrDesktop: 'desktop'
+            os: ubuntu-latest
+          - jupyter: remote
+            python: nonConda
+            pythonVersion: '3.9'
+            webOrDesktop: 'web'
+            os: ubuntu-latest
+          - jupyter: raw
+            python: noPython
+            os: ubuntu-latest
+          - jupyter: raw
+            python: nonConda
+            pythonVersion: '3.10'
+            os: windows-latest
+          - jupyter: local
+            python: nonConda
+            pythonVersion: '3.9'
+            packageVersion: 'prerelease'
+            os: ubuntu-latest
+          - jupyter: raw
+            python: nonConda
+            pythonVersion: '3.9'
+            packageVersion: 'prerelease'
+            os: ubuntu-latest
+        exclude:
+          - python: conda # Conda does't seem to support 3.10 yet.
+            pythonVersion: '3.10'
+        #   - pythonVersion: '3.9'
         #     python: nonConda
-        #     pythonVersion: '3.9'
-        #     webOrDesktop: 'desktop'
-        #     os: ubuntu-latest
-        #   - jupyter: remote
-        #     python: nonConda
-        #     pythonVersion: '3.9'
-        #     webOrDesktop: 'web'
-        #     os: ubuntu-latest
-        #   - jupyter: raw
-        #     python: noPython
-        #     os: ubuntu-latest
-        #   - jupyter: raw
-        #     python: nonConda
-        #     pythonVersion: '3.10'
+        #     jupyter: raw
         #     os: windows-latest
-        #   - jupyter: local
-        #     python: nonConda
-        #     pythonVersion: '3.9'
-        #     packageVersion: 'prerelease'
-        #     os: ubuntu-latest
-        #   - jupyter: raw
-        #     python: nonConda
-        #     pythonVersion: '3.9'
-        #     packageVersion: 'prerelease'
-        #     os: ubuntu-latest
-        # exclude:
-        #   - python: conda # Conda does't seem to support 3.10 yet.
-        #     pythonVersion: '3.10'
-        # #   - pythonVersion: '3.9'
-        # #     python: nonConda
-        # #     jupyter: raw
-        # #     os: windows-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v2
@@ -471,3 +682,225 @@ jobs:
 
       - name: Verify there are no unhandled errors
         run: npm run verifyUnhandledErrors
+
+  smoke-tests:
+    timeout-minutes: 30
+    name: Smoke tests
+    # The value of runs-on is the OS of the current job (specified in the strategy matrix below) instead of being hardcoded.
+    runs-on: ${{ matrix.os }}
+    if: github.repository == 'microsoft/vscode-jupyter'
+    needs: [build-vsix]
+    env:
+      VSIX_NAME: 'ms-toolsai-jupyter-insiders.vsix'
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [ubuntu-latest, windows-latest, macos-latest]
+        python: [3.9]
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Use Python ${{matrix.python}}
+        uses: actions/setup-python@v2
+        with:
+          python-version: ${{matrix.python}}
+
+      - name: Set CI Path
+        uses: ./.github/actions/set-python
+        id: set-python
+        with:
+          PYTHON_VERSION: ${{matrix.python}}
+
+      - name: Upgrade pip
+        run: python -m pip install -U pip
+
+      - name: Use Node ${{env.NODE_VERSION}}
+        uses: actions/setup-node@v2.4.1
+        with:
+          node-version: ${{env.NODE_VERSION}}
+
+      - name: Download VSIX
+        uses: actions/download-artifact@v2
+        with:
+          name: 'ms-toolsai-jupyter-insiders.vsix'
+
+      - name: Install dependencies (npm ci)
+        run: npm ci --prefer-offline
+
+      - name: pip install system test requirements
+        run: |
+          python -m pip install --upgrade -r build/venv-test-requirements.txt
+          python -m pip --disable-pip-version-check install -t ./pythonFiles/lib/python --no-cache-dir --implementation py --no-deps --upgrade -r requirements.txt
+        shell: bash
+
+      # Compile the test files.
+      - name: Prepare for smoke tests
+        run: npx tsc -p ./
+        shell: bash
+
+      - name: Run desktop smoke tests
+        env:
+          DISPLAY: 10
+        uses: GabrielBB/xvfb-action@v1.4
+        with:
+          run: npm run testSmokeLogged
+
+      - name: Upload smoke-test log
+        uses: actions/upload-artifact@v2
+        if: failure()
+        with:
+          name: smoke-test-${{matrix.os}}.log
+          path: './smoke-test.log'
+
+      - name: Create coverage folder (if not created)
+        run: npm run createNycFolder
+
+      # Upload unit test coverage reports for later use in the "reports" job.
+      - name: Upload unit test coverage reports
+        uses: actions/upload-artifact@v2
+        if: always()
+        with:
+          name: ${{runner.os}}-${{env.COVERAGE_REPORTS}}
+          path: .nyc_output
+          retention-days: 1
+
+  perf-tests:
+    timeout-minutes: 30
+    name: Performance tests
+    # The value of runs-on is the OS of the current job (specified in the strategy matrix below) instead of being hardcoded.
+    runs-on: ${{ matrix.os }}
+    if: github.repository == 'microsoft/vscode-jupyter'
+    needs: [build-vsix]
+    env:
+      VSIX_NAME: 'ms-toolsai-jupyter-insiders.vsix'
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [ubuntu-latest, windows-latest, macos-latest]
+        python: [3.9]
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Use Python ${{matrix.python}}
+        uses: actions/setup-python@v2
+        with:
+          python-version: ${{matrix.python}}
+
+      - name: Set CI Path
+        uses: ./.github/actions/set-python
+        id: set-python
+        with:
+          PYTHON_VERSION: ${{matrix.python}}
+
+      - name: Upgrade pip
+        run: python -m pip install -U pip
+
+      - name: Use Node ${{env.NODE_VERSION}}
+        uses: actions/setup-node@v2.4.1
+        with:
+          node-version: ${{env.NODE_VERSION}}
+
+      - name: Download VSIX
+        uses: actions/download-artifact@v2
+        with:
+          name: 'ms-toolsai-jupyter-insiders.vsix'
+
+      - name: Install dependencies (npm ci)
+        run: npm ci --prefer-offline
+
+      - name: pip install system test requirements
+        run: |
+          python -m pip install --upgrade -r build/venv-test-requirements.txt
+          python -m pip --disable-pip-version-check install -t ./pythonFiles/lib/python --no-cache-dir --implementation py --no-deps --upgrade -r requirements.txt
+        shell: bash
+
+      # Compile the test files.
+      - name: Prepare for perf tests
+        run: npx tsc -p ./
+        shell: bash
+
+      - name: Run desktop perf tests
+        env:
+          DISPLAY: 10
+        uses: GabrielBB/xvfb-action@v1.4
+        with:
+          run: npm run testPerformance
+
+      - name: Upload screenshots
+        uses: actions/upload-artifact@v2
+        if: always()
+        with:
+          name: Screenshots-perf-${{matrix.os}}
+          path: './${{env.IPYWIDGET_SCREENSHOT_PATH}}'
+          retention-days: 1
+
+  coverage:
+    name: Coverage reports upload
+    runs-on: ubuntu-latest
+    if: "(success() || failure()) && !contains(github.ref, 'refs/heads/release')"
+    needs: [ts_tests, vscodeTests, smoke-tests]
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Install Node
+        uses: actions/setup-node@v2.4.1
+        with:
+          node-version: ${{env.NODE_VERSION}}
+
+      - name: Install dependencies (npm ci)
+        run: npm ci --prefer-offline
+
+      - name: Cache compiled TS files
+        id: out-cache
+        uses: actions/cache@v3
+        with:
+          path: ./out
+          key: ${{runner.os}}-${{env.CACHE_OUT_DIRECTORY}}-${{hashFiles('src/**')}}
+
+      - name: Compile if not cached
+        run: npm run prePublishNonBundle
+        if: steps.out-cache.outputs.cache-hit != 'true'
+        env:
+          CI_JUPYTER_FAST_COMPILATION: 'true'
+
+      # It isn't possible to specify a regex for artifact names, so we have to download each artifact manually.
+      # The name pattern is ${{runner.os}}-${{env.COVERAGE_REPORTS}}, and possible values for runner.os are `Linux`, `Windows`, or `macOS`.
+      # See https://help.github.com/en/actions/reference/contexts-and-expression-syntax-for-github-actions#runner-context
+      - name: Download Ubuntu test coverage artifacts
+        uses: actions/download-artifact@v2
+        with:
+          name: ${{runner.os}}-${{ env.COVERAGE_REPORTS }}
+          path: ${{runner.os}}-${{ env.COVERAGE_REPORTS }}
+
+      - name: Extract Ubuntu coverage artifacts to ./nyc_output
+        run: |
+          pwd
+          mkdir .nyc_output
+          mv ${{runner.os}}-${{ env.COVERAGE_REPORTS }}/* .nyc_output
+          rm -r ${{runner.os}}-${{ env.COVERAGE_REPORTS }}
+
+      - name: Merge coverage reports
+        run: |
+          pwd
+          npx nyc merge ./.nyc_output
+          rm -r .nyc_output
+          mkdir .nyc_output
+          mv coverage.json ./.nyc_output
+        continue-on-error: true
+
+      - name: Generate coverage reports
+        run: npm run test:cover:report
+        continue-on-error: true
+
+      - name: Upload coverage to codecov
+        uses: codecov/codecov-action@v1
+        with:
+          token: ${{ secrets.CODECOV_TOKEN }}
+          file: ./coverage/cobertura-coverage.xml
+          path_to_write_report: ./coverage/codecov_report.txt
+      # Alternative method for uploading
+      # - name: Upload coverage to codecov
+      #  run: bash <(curl -s https://codecov.io/bash) -f ./coverage/cobertura-coverage.xml -v
